# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start app with docker compose
      run: docker-compose up
    - timeout-minutes: 5
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: wait for docker compose
      run: sleep 180
    - name: run tests
      run: npm test
      continue-on-error: true
    - name: stop docker containers
      run: docker stop dvna-dep_mysql-db_1 dvna-dep_app_1
      
