# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start app in background with docker compose
      run: docker-compose up -d
    - name: wait for app to spin up, run npm tests
      run: sleep 120; npm test
    - name: stop docker containers
      run: docker stop dvna-dep_app_1; docker stop dvna-dep_mysql-db_1
