# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start app with docker compose
      run: docker-compose up
  test:
    - name: run tests
    steps:
    - uses: actions/checkout@v2
    - name: wait for docker compose
      run: sleep 180
    - name: run tests
      run: npm test
